name = "ElectronPhonon"
uuid = "c748efe2-6859-4c1c-b19c-5ce0d054679a"
authors = ["Aleksandr Poliukhin, Francesco Libbi"]
version = "1.0.0-DEV"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FortranFiles = "c58ffaec-ab22-586d-bfc5-781a99fd0b10"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"


[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
ElectronPhononCUDAExt = "CUDA"

[compat]
CondaPkg = "0.2.33"
HDF5 = "0.17.2"
JSON3 = "1.14.3"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
